publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
enablePrePostScripts: true
nodeLinker: hoisted
publishBranch: main
allowBuilds:
  '@vscode/vsce-sign': true
  keytar: true
  unrs-resolver: true
